name: deploy project
on:
  push:
    branches:
      - dev-for-outsourcing
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Install and build project
        run: |
          yarn install
          yarn buildWithPrefix

      - name: Upload project to CDN
        run: |
          node scripts/upload.js ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }}

      - name: Deploy by ssh
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "./build"
          REMOTE_HOST: "47.99.245.139"
          REMOTE_USER: "root"
          TARGET: "/home/oj/website/build/"
